name: Minishift E2E
on: pull_request
jobs:
  minishift-e2e:
    name: Operator installer
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and start minishift OCP 3.11 cluster
      run: |
        brew cask install minishift
        export MINISHIFT_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        minishift start --memory=5500 --vm-driver=virtualbox
    - name: Generate minishift certificates
      run: |
        export CA_CN="Local Eclipse Che Signer"
        export DOMAIN=\*.$( minishift ip ).nip.io
        export OPENSSL_CNF=/System/Library/OpenSSL/openssl.cnf
        openssl genrsa -out ca.key 4096
        openssl req -x509 \
          -new -nodes \
          -key ca.key \
          -sha256 \
          -days 1024 \
          -out ca.crt \
          -subj /CN="${CA_CN}" \
          -reqexts SAN \
          -extensions SAN \
          -config <(cat ${OPENSSL_CNF} \
              <(printf '[SAN]\nbasicConstraints=critical, CA:TRUE\nkeyUsage=keyCertSign, cRLSign, digitalSignature'))
        openssl genrsa -out domain.key 2048
        openssl req -new -sha256 \
          -key domain.key \
          -subj "/O=Local Eclipse Che/CN=${DOMAIN}" \
          -reqexts SAN \
          -config <(cat ${OPENSSL_CNF} \
              <(printf "\n[SAN]\nsubjectAltName=DNS:${DOMAIN}\nbasicConstraints=critical, CA:FALSE\nkeyUsage=digitalSignature, keyEncipherment, keyAgreement, dataEncipherment\nextendedKeyUsage=serverAuth")) \
          -out domain.csr
        openssl x509 \
          -req \
          -sha256 \
          -extfile <(printf "subjectAltName=DNS:${DOMAIN}\nbasicConstraints=critical, CA:FALSE\nkeyUsage=digitalSignature, keyEncipherment, keyAgreement, dataEncipherment\nextendedKeyUsage=serverAuth") \
          -days 365 \
          -in domain.csr \
          -CA ca.crt \
          -CAkey ca.key \
          -CAcreateserial -out domain.crt
    - name: Update minishift deprecated certificates 
      run: |
        sleep 30
        eval $(minishift oc-env)
        oc login -u system:admin --insecure-skip-tls-verify=true
        oc create namespace eclipse-che
        oc project default
        oc delete secret router-certs
        cat domain.crt domain.key > minishift.crt
        oc create secret tls router-certs --key=domain.key --cert=minishift.crt
        sleep 5s
        # oc rollout latest router
        oc create secret generic self-signed-certificate --from-file=ca.crt -n=eclipse-che
        # RUN THE TESTS
    - name: Start che
      run: |
        bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
        chectl server:deploy --k8spodreadytimeout=180000 --k8spoddownloadimagetimeout=600000 --k8spodwaittimeout=600000 --installer=operator --listr-renderer=verbose --platform=minishift --chenamespace=eclipse-che
        chectl auth:login -u developer -p anything --chenamespace=eclipse-che
        chectl worksapce:create --start 